name: quiz_game
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^2.0.7
  audioplayers: ^6.6.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/image_game.svg
     - assets/ANANAS.jpg
     - assets/BANANE.jpg
     - assets/FRAISE.jpg
     - assets/MANGUE.jpg
     - assets/PAPAYE.jpg
     - assets/PASTEQUES.jpg
     - assets/POMME.jpg
     - assets/RAISIN.jpg
     - assets/date.jpg
     - assets/lost.wav
     - assets/win.wav




